import { TIER2_TIER3_CITIES, DEFAULT_PLATFORM_SETTINGS } from '@myride/constants';
import { IUser, IVehicle, IBooking, IPlatformSettings, IHostEarning } from '@myride/types';

export interface InMemoryDb {
  users: IUser[];
  vehicles: IVehicle[];
  bookings: IBooking[];
  settings: IPlatformSettings;
  earnings: IHostEarning[];
  reviews?: any[];
  auditLogs: any[];
  payments: any[];
}

export const memoryStore: InMemoryDb = {
  users: [
    {
      _id: 'user_cust_1',
      id: 'user_cust_1',
      name: 'Rahul Sharma',
      phone: '9876543210',
      email: 'rahul@example.com',
      role: 'CUSTOMER',
      city: 'Lucknow',
      isVerified: true,
      kycStatus: 'VERIFIED',
      drivingLicenseNumber: 'UP3220200012345',
      drivingLicenseVerified: true,
      rating: 4.9,
      totalTrips: 8,
      walletBalance: 500,
      referralCode: 'RAHUL98',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'user_host_1',
      id: 'user_host_1',
      name: 'Amitabh Verma',
      phone: '9876500001',
      email: 'amitabh@example.com',
      role: 'HOST',
      city: 'Lucknow',
      isVerified: true,
      kycStatus: 'VERIFIED',
      rating: 4.95,
      totalTrips: 34,
      walletBalance: 4250,
      referralCode: 'AMITABH10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'user_admin_1',
      id: 'user_admin_1',
      name: 'MyRide Admin',
      phone: '9999999999',
      email: 'admin@myride.in',
      role: 'ADMIN',
      city: 'Lucknow',
      isVerified: true,
      kycStatus: 'VERIFIED',
      rating: 5.0,
      totalTrips: 0,
      walletBalance: 0,
      referralCode: 'ADMIN01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  vehicles: [
    {
      _id: 'veh_1',
      id: 'veh_1',
      ownerId: 'user_host_1',
      ownerName: 'Amitabh Verma',
      ownerPhone: '9876500001',
      ownerRating: 4.95,
      isHostVerified: true,
      brand: 'Hyundai',
      model: 'Creta SX (O)',
      year: 2023,
      type: 'CAR',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 5,
      registrationNumber: 'UP32 AB 1234',
      pricing: {
        dailyRate: 2499,
        hourlyRate: 150,
        securityDeposit: 3000,
        deliveryFee: 299,
      },
      securityDeposit: 3000,
      location: {
        type: 'Point',
        coordinates: [80.9462, 26.8467],
        address: 'Hazratganj Metro Hub',
        area: 'Hazratganj',
        city: 'Lucknow',
        state: 'Uttar Pradesh',
      },
      images: [
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&auto=format&fit=crop&q=80',
      ],
      features: ['Sunroof', 'Touchscreen Infotainment', 'Ventilated Seats', 'GPS Navigation', 'Fastag Enabled'],
      guidelines: ['Return with same fuel level', 'Valid Driving License required', 'No smoking'],
      availability: {
        isAvailable: true,
      },
      verificationStatus: 'APPROVED',
      rating: 4.9,
      totalTrips: 28,
      deliveryAvailable: true,
      instantBooking: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'veh_2',
      id: 'veh_2',
      ownerId: 'user_host_1',
      ownerName: 'Amitabh Verma',
      ownerPhone: '9876500001',
      ownerRating: 4.95,
      isHostVerified: true,
      brand: 'Maruti Suzuki',
      model: 'Swift ZXi',
      year: 2022,
      type: 'CAR',
      fuelType: 'Petrol',
      transmission: 'Manual',
      seats: 5,
      registrationNumber: 'UP32 XY 9876',
      pricing: {
        dailyRate: 1499,
        hourlyRate: 90,
        securityDeposit: 2000,
        deliveryFee: 199,
      },
      securityDeposit: 2000,
      location: {
        type: 'Point',
        coordinates: [80.9992, 26.8524],
        address: 'Gomti Nagar Pickup Hub',
        area: 'Gomti Nagar',
        city: 'Lucknow',
        state: 'Uttar Pradesh',
      },
      images: [
        'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&auto=format&fit=crop&q=80',
      ],
      features: ['Apple CarPlay / Android Auto', 'Air Conditioning', 'Airbags', 'Fastag Enabled'],
      guidelines: ['Self-drive only', 'Speed limit 100 km/h'],
      availability: {
        isAvailable: true,
      },
      verificationStatus: 'APPROVED',
      rating: 4.8,
      totalTrips: 42,
      deliveryAvailable: true,
      instantBooking: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'veh_3',
      id: 'veh_3',
      ownerId: 'user_host_1',
      ownerName: 'Amitabh Verma',
      ownerPhone: '9876500001',
      ownerRating: 4.95,
      isHostVerified: true,
      brand: 'Royal Enfield',
      model: 'Classic 350',
      year: 2023,
      type: 'BIKE',
      fuelType: 'Petrol',
      transmission: 'Manual',
      seats: 2,
      registrationNumber: 'UP32 RE 3500',
      pricing: {
        dailyRate: 899,
        hourlyRate: 60,
        securityDeposit: 1500,
        deliveryFee: 149,
      },
      securityDeposit: 1500,
      location: {
        type: 'Point',
        coordinates: [80.9221, 26.8322],
        address: 'Charbagh Railway Hub',
        area: 'Charbagh',
        city: 'Lucknow',
        state: 'Uttar Pradesh',
      },
      images: [
        'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&auto=format&fit=crop&q=80',
      ],
      features: ['Dual-channel ABS', 'Mobile Mount & Charger', 'Two Helmets Included'],
      guidelines: ['Helmet mandatory for rider and pillion', 'Valid 2-wheeler license'],
      availability: {
        isAvailable: true,
      },
      verificationStatus: 'APPROVED',
      rating: 4.95,
      totalTrips: 35,
      deliveryAvailable: true,
      instantBooking: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'veh_4',
      id: 'veh_4',
      ownerId: 'user_host_1',
      ownerName: 'Amitabh Verma',
      ownerRating: 4.95,
      isHostVerified: true,
      brand: 'Tata',
      model: 'Nexon EV Max',
      year: 2023,
      type: 'EV',
      fuelType: 'Electric',
      transmission: 'Automatic',
      seats: 5,
      registrationNumber: 'RJ14 EV 4321',
      pricing: {
        dailyRate: 2199,
        hourlyRate: 140,
        securityDeposit: 2500,
        deliveryFee: 249,
      },
      securityDeposit: 2500,
      location: {
        type: 'Point',
        coordinates: [75.7667, 26.8589],
        address: 'Mansarovar Metro Hub',
        area: 'Mansarovar',
        city: 'Jaipur',
        state: 'Rajasthan',
      },
      images: [
        'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=80',
      ],
      features: ['400km Real Range', 'Fast Charging Cable Included', 'Cruise Control'],
      guidelines: ['Return with at least 25% battery'],
      availability: {
        isAvailable: true,
      },
      verificationStatus: 'APPROVED',
      rating: 4.88,
      totalTrips: 19,
      deliveryAvailable: true,
      instantBooking: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'veh_5',
      id: 'veh_5',
      ownerId: 'user_host_1',
      ownerName: 'Amitabh Verma',
      ownerRating: 4.95,
      isHostVerified: true,
      brand: 'Mahindra',
      model: 'Scorpio-N Z8L',
      year: 2024,
      type: 'SUV',
      fuelType: 'Diesel',
      transmission: 'Automatic',
      seats: 7,
      registrationNumber: 'MP09 SC 7777',
      pricing: {
        dailyRate: 3199,
        hourlyRate: 200,
        securityDeposit: 4000,
        deliveryFee: 349,
      },
      securityDeposit: 4000,
      location: {
        type: 'Point',
        coordinates: [75.8937, 22.7533],
        address: 'Vijay Nagar Square Hub',
        area: 'Vijay Nagar',
        city: 'Indore',
        state: 'Madhya Pradesh',
      },
      images: [
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80',
      ],
      features: ['4XPLOR Terrain Modes', 'Sony 3D Sound System', 'Sunroof', '7 Captain Seats'],
      guidelines: ['Over-speeding capped at 110 km/h'],
      availability: {
        isAvailable: true,
      },
      verificationStatus: 'APPROVED',
      rating: 5.0,
      totalTrips: 14,
      deliveryAvailable: true,
      instantBooking: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  bookings: [
    {
      _id: 'book_sample_1',
      id: 'book_sample_1',
      bookingId: 'MYR-984210',
      customerId: 'user_cust_1',
      customerName: 'Rahul Sharma',
      customerPhone: '9876543210',
      hostId: 'user_host_1',
      hostName: 'Amitabh Verma',
      hostPhone: '9876500001',
      vehicleId: 'veh_1',
      vehicle: null as any,
      startDateTime: new Date(Date.now() - 86400000 * 2).toISOString(),
      endDateTime: new Date(Date.now() - 86400000 * 1).toISOString(),
      durationDays: 1,
      pickupType: 'self_pickup',
      pickupLocation: 'Hazratganj Metro Station Hub, Lucknow',
      dropoffLocation: 'Hazratganj Metro Station Hub, Lucknow',
      pricing: {
        baseAmount: 2499,
        durationDays: 1,
        deliveryFee: 0,
        commissionRate: 15,
        commissionAmount: 375,
        hostEarnings: 2124,
        taxes: 68,
        discount: 0,
        securityDeposit: 3000,
        totalAmount: 5942,
      },
      bookingStatus: 'COMPLETED',
      paymentStatus: 'completed',
      startInspection: {
        odometerReading: 14250,
        fuelLevelPercentage: 90,
        photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800'],
        checklist: {
          lightsWorking: true,
          tyresInspected: true,
          acHeaterWorking: true,
          accessoriesPresent: true,
          documentsPresent: true,
        },
        timestamp: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
      endInspection: {
        odometerReading: 14410,
        fuelLevelPercentage: 88,
        photos: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800'],
        checklist: {
          lightsWorking: true,
          tyresInspected: true,
          acHeaterWorking: true,
          accessoriesPresent: true,
          documentsPresent: true,
        },
        timestamp: new Date(Date.now() - 86400000 * 1).toISOString(),
      },
      createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
      updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    },
  ],
  settings: {
    commission: {
      defaultPercentage: 15, // 15% Platform Commission
      bikePercentage: 12,
      scooterPercentage: 12,
      carPercentage: 15,
      suvPercentage: 15,
      evPercentage: 10,
    },
    referral: {
      referrerReward: 200,
      referredDiscount: 150,
    },
    taxes: {
      gstPercentage: 18,
    },
    delivery: {
      baseDeliveryFee: 150,
      perKmFee: 15,
    },
    support: {
      phone: '+91 8000 123 456',
      email: 'support@myride.in',
      emergencyPhone: '112',
      roadsidePhone: '+91 1800 555 789',
    },
    supportedCities: ['Lucknow', 'Jaipur', 'Indore', 'Bhopal', 'Patna', 'Kanpur', 'Chandigarh'],
    updatedAt: new Date().toISOString(),
  },
  earnings: [
    {
      _id: 'earn_1',
      id: 'earn_1',
      hostId: 'user_host_1',
      bookingId: 'book_sample_1',
      vehicleId: 'veh_1',
      vehicleName: 'Hyundai Creta SX (O)',
      grossAmount: 2499,
      commissionPercentage: 15,
      commissionAmount: 375,
      netAmount: 2124,
      status: 'AVAILABLE',
      tripDate: new Date(Date.now() - 86400000 * 2).toISOString(),
      createdAt: new Date().toISOString(),
    },
  ],
  auditLogs: [
    {
      action: 'SYSTEM_BOOT',
      details: 'MyRide Platform initialized with 15% configurable commission rule.',
      timestamp: new Date().toISOString(),
    },
  ],
  payments: [],
};
