export const en = {
  // Common
  appName: 'MyRide',
  tagline: 'Apni Ride. Apna Choice.',
  altTagline: 'Ride Local. Ride Your Way.',
  searchRides: 'Search Rides',
  bookNow: 'Book Now',
  viewDetails: 'View Details',
  filter: 'Filter',
  sort: 'Sort',
  save: 'Save',
  cancel: 'Cancel',
  confirm: 'Confirm',
  apply: 'Apply',
  reset: 'Reset',
  skip: 'Skip',
  next: 'Next',
  getStarted: 'Get Started',
  loading: 'Loading...',
  
  // Home
  whereAreYouRiding: 'Where are you riding today?',
  pickupLocation: 'Pick-up Location',
  startDateAndTime: 'Start Date & Time',
  endDateAndTime: 'End Date & Time',
  popularNearYou: 'Popular Near You',
  quickCategories: 'Quick Categories',
  welcomeBack: 'Welcome back 👋',
  findFirstRide: 'Find your first ride 🚗',
  bikes: 'Bikes',
  cars: 'Cars',
  suvs: 'SUVs',
  evs: 'EVs',
  kmAway: 'km away',
  day: 'day',
  
  // Vehicle Details
  verifiedHost: 'Verified Host',
  features: 'Key Features',
  pickupLocationTitle: 'Pick-up Location',
  pricingBreakdown: 'Pricing Breakdown',
  baseRental: 'Base Rental',
  securityDeposit: 'Refundable Security Deposit',
  myRideFee: 'MyRide Platform Fee (15%)',
  totalPayable: 'Total Payable',
  hostInfo: 'Host Information',
  tripsCompleted: 'Trips Completed',
  responseRate: 'Response Rate',
  chatWithHost: 'Chat with Host',
  
  // Booking
  bookingTitle: 'Complete Booking',
  step1: 'Dates',
  step2: 'Pickup',
  step3: 'Review',
  step4: 'Payment',
  selfPickup: 'Self Pickup',
  hostDelivery: 'Host Delivery',
  bookingConfirmed: 'Booking Confirmed 🎉',
  bookingId: 'Booking ID',
  cancellationPolicyTitle: 'Cancellation & Refund Policy',
  freeCancellation24h: 'Free Cancellation (100% Refund)',
  freeCancellation24hDesc: 'Cancel 24+ hours before ride start to receive a full 100% refund.',
  noRefundWithin24h: 'Non-Refundable (0% Refund)',
  noRefundWithin24hDesc: 'Cancellations within 24 hours of ride start are non-refundable (0% refund).',
  hostChangePolicyTitle: 'Host Ride Modification Policy',
  hostChangePolicyDesc: 'Rides can be changed directly 24+ hours before start. Within 24 hours, you must inform the customer first.',
  hostMustInformCustomer: 'Host Must Inform Customer First',
  hostInformedConfirmation: 'I have contacted and informed the customer about this modification/cancellation.',
  changeRide: 'Change Ride',
  
  // Host
  hostDashboard: 'Host Dashboard',
  goodMorning: 'Good Morning',
  totalEarnings: 'Total Earnings',
  thisMonth: 'This Month',
  activeRentals: 'Active Rentals',
  totalTrips: 'Total Trips',
  yourVehicles: 'Your Vehicles',
  listNewVehicle: 'List New Vehicle',
  grossEarnings: 'Gross Earnings',
  platformCommission: 'MyRide Commission (15%)',
  netEarnings: 'Net Earnings',
  withdrawEarnings: 'Withdraw Earnings',
  
  // Profile
  customerMode: 'Customer Mode',
  hostMode: 'Host Mode',
  switchRole: 'Switch to Host',
  switchCustomer: 'Switch to Customer',
  savedVehicles: 'Saved Rides',
  myBookings: 'My Bookings',
  safetyCenter: 'Safety Center',
  referAndEarn: 'Refer & Earn',
  offers: 'Offers & Discounts',
  language: 'App Language',
  logout: 'Logout',
};
