import { en } from './en';

export const hi: typeof en = {
  // Common
  appName: 'MyRide',
  tagline: 'अपनी राइड. अपनी चॉइस.',
  altTagline: 'लोकल राइड. अपने अंदाज़ में.',
  searchRides: 'गाड़ी खोजें',
  bookNow: 'अभी बुक करें',
  viewDetails: 'विवरण देखें',
  filter: 'फ़िल्टर',
  sort: 'क्रमबद्ध करें',
  save: 'सेव करें',
  cancel: 'रद्द करें',
  confirm: 'पुष्टि करें',
  apply: 'लागू करें',
  reset: 'रीसेट',
  skip: 'छोड़ें',
  next: 'आगे बढ़ें',
  getStarted: 'शुरू करें',
  loading: 'लोड हो रहा है...',
  
  // Home
  whereAreYouRiding: 'आज आप कहाँ की राइड लेंगे?',
  pickupLocation: 'पिक-अप स्थान',
  startDateAndTime: 'शुरुआत की तारीख व समय',
  endDateAndTime: 'वापसी की तारीख व समय',
  popularNearYou: 'आपके नज़दीक लोकप्रिय गाड़ियाँ',
  quickCategories: 'श्रेणियाँ',
  welcomeBack: 'वापसी पर स्वागत है 👋',
  findFirstRide: 'अपनी पहली राइड खोजें 🚗',
  bikes: 'बाइक / स्कूटर',
  cars: 'कारें',
  suvs: 'एसयूवी',
  evs: 'ईवी (इलेक्ट्रिक)',
  kmAway: 'किमी दूर',
  day: 'दिन',
  
  // Vehicle Details
  verifiedHost: 'सत्यापित होस्ट',
  features: 'मुख्य विशेषताएं',
  pickupLocationTitle: 'पिक-अप स्थान',
  pricingBreakdown: 'किराया विवरण',
  baseRental: 'मूल किराया',
  securityDeposit: 'वापसी योग्य सिक्योरिटी डिपॉजिट',
  myRideFee: 'MyRide प्लेटफ़ॉर्म शुल्क (15%)',
  totalPayable: 'कुल देय राशि',
  hostInfo: 'होस्ट की जानकारी',
  tripsCompleted: 'सफ़र पूरे किए',
  responseRate: 'रिस्पॉन्स दर',
  chatWithHost: 'होस्ट से बात करें',
  
  // Booking
  bookingTitle: 'बुकिंग पूरी करें',
  step1: 'तारीख',
  step2: 'पिकअप',
  step3: 'समीक्षा',
  step4: 'भुगतान',
  selfPickup: 'स्वयं पिकअप',
  hostDelivery: 'घर पर डिलीवरी',
  bookingConfirmed: 'बुकिंग कन्फर्म हो गई 🎉',
  bookingId: 'बुकिंग आईडी',
  cancellationPolicyTitle: 'रद्दीकरण एवं रिफंड नीति',
  freeCancellation24h: 'मुफ़्त रद्दीकरण (100% रिफंड)',
  freeCancellation24hDesc: 'सवारी शुरू होने से 24+ घंटे पहले रद्द करने पर 100% पूरा रिफंड वापस मिलेगा।',
  noRefundWithin24h: 'नॉन-रिफंडेबल (0% रिफंड)',
  noRefundWithin24hDesc: 'सवारी शुरू होने के 24 घंटे के भीतर रद्द करने पर कोई रिफंड नहीं मिलेगा (0% रिफंड)।',
  hostChangePolicyTitle: 'होस्ट सवारी संशोधन नीति',
  hostChangePolicyDesc: 'सवारी शुरू होने से 24+ घंटे पहले सीधे बदलाव संभव हैं। 24 घंटे के अंदर ग्राहक को पहले सूचित करना अनिवार्य है।',
  hostMustInformCustomer: 'होस्ट द्वारा ग्राहक को पहले सूचित करना अनिवार्य',
  hostInformedConfirmation: 'मैंने इस बदलाव/रद्दीकरण के बारे में ग्राहक से बात करके उन्हें सूचित कर दिया है।',
  changeRide: 'सवारी बदलें',
  
  // Host
  hostDashboard: 'होस्ट डैशबोर्ड',
  goodMorning: 'शुभ प्रभात',
  totalEarnings: 'कुल कमाई',
  thisMonth: 'इस महीने',
  activeRentals: 'सक्रिय किराए',
  totalTrips: 'कुल ट्रिप्स',
  yourVehicles: 'आपकी गाड़ियाँ',
  listNewVehicle: 'नई गाड़ी जोड़ें',
  grossEarnings: 'सकल कमाई',
  platformCommission: 'MyRide कमीशन (15%)',
  netEarnings: 'शुद्ध कमाई',
  withdrawEarnings: 'पैसे निकालें',
  
  // Profile
  customerMode: 'कस्टमर मोड',
  hostMode: 'होस्ट मोड',
  switchRole: 'होस्ट मोड में जाएं',
  switchCustomer: 'कस्टमर मोड में जाएं',
  savedVehicles: 'पसंदीदा गाड़ियाँ',
  myBookings: 'मेरी बुकिंग्स',
  safetyCenter: 'सुरक्षा केंद्र',
  referAndEarn: 'रेफ़र करें और कमाएं',
  offers: 'ऑफ़र्स और छूट',
  language: 'ऐप की भाषा',
  logout: 'लॉगआउट',
};
