import { en } from './en';

export const hinglish: typeof en = {
  // Common
  appName: 'MyRide',
  tagline: 'Apni Ride. Apna Choice.',
  altTagline: 'Ride Local. Apne Style Me.',
  searchRides: 'Ride Search Karein',
  bookNow: 'Abhi Book Karein',
  viewDetails: 'Details Dekhein',
  filter: 'Filter Karein',
  sort: 'Sort Karein',
  save: 'Save Karein',
  cancel: 'Cancel Karein',
  confirm: 'Confirm Karein',
  apply: 'Apply Karein',
  reset: 'Reset Karein',
  skip: 'Skip Karein',
  next: 'Next',
  getStarted: 'Shuru Karein',
  loading: 'Load ho raha hai...',
  
  // Home
  whereAreYouRiding: 'Aaj kahan ride le jaana hai?',
  pickupLocation: 'Pick-up Location',
  startDateAndTime: 'Start Date & Time',
  endDateAndTime: 'Return Date & Time',
  popularNearYou: 'Aapke Paas Popular Rides',
  quickCategories: 'Categories',
  welcomeBack: 'Welcome back dost 👋',
  findFirstRide: 'Apni pehli ride dhoondhein 🚗',
  bikes: 'Bikes & Scooters',
  cars: 'Cars',
  suvs: 'SUVs',
  evs: 'EVs',
  kmAway: 'km door',
  day: 'din',
  
  // Vehicle Details
  verifiedHost: 'Verified Host',
  features: 'Gaadi ke Features',
  pickupLocationTitle: 'Pick-up Location',
  pricingBreakdown: 'Kiraya Breakdown',
  baseRental: 'Base Rental',
  securityDeposit: 'Refundable Security Deposit',
  myRideFee: 'MyRide Platform Fee (15%)',
  totalPayable: 'Total Payable Amount',
  hostInfo: 'Host ki Jankari',
  tripsCompleted: 'Trips Complete kiye',
  responseRate: 'Response Rate',
  chatWithHost: 'Host se Chat Karein',
  
  // Booking
  bookingTitle: 'Booking Complete Karein',
  step1: 'Dates',
  step2: 'Pickup',
  step3: 'Review',
  step4: 'Payment',
  selfPickup: 'Self Pickup (Khud lein)',
  hostDelivery: 'Ghar par Delivery',
  bookingConfirmed: 'Booking Confirm ho gayi 🎉',
  bookingId: 'Booking ID',
  cancellationPolicyTitle: 'Cancellation aur Refund Policy',
  freeCancellation24h: 'Free Cancellation (100% Refund)',
  freeCancellation24hDesc: 'Ride shuru hone se 24+ ghante pehle cancel karein to 100% full refund milega.',
  noRefundWithin24h: 'Non-Refundable (0% Refund)',
  noRefundWithin24hDesc: 'Ride shuru hone ke 24 ghante ke andar cancel karne par 0% refund milega.',
  hostChangePolicyTitle: 'Host Ride Change Policy',
  hostChangePolicyDesc: 'Ride 24+ ghante pehle directly change kar sakte hain. 24 ghante ke andar customer ko pehle inform karna zaroori hai.',
  hostMustInformCustomer: 'Host ko Customer ko pehle inform karna mandatory hai',
  hostInformedConfirmation: 'Maine customer se contact karke unhe inform kar diya hai.',
  changeRide: 'Ride Change Karein',
  
  // Host
  hostDashboard: 'Host Dashboard',
  goodMorning: 'Good Morning',
  totalEarnings: 'Total Kamai',
  thisMonth: 'Is Mahine ki Kamai',
  activeRentals: 'Active Rentals',
  totalTrips: 'Total Trips',
  yourVehicles: 'Aapki Gaadiyan',
  listNewVehicle: 'Nayi Gaadi List Karein',
  grossEarnings: 'Gross Earnings',
  platformCommission: 'MyRide Commission (15%)',
  netEarnings: 'Aapki Net Kamai',
  withdrawEarnings: 'Paise Bank Me Transfer Karein',
  
  // Profile
  customerMode: 'Customer Mode',
  hostMode: 'Host Mode',
  switchRole: 'Host Banein (Kamai Karein)',
  switchCustomer: 'Customer Mode me jaayein',
  savedVehicles: 'Saved Rides',
  myBookings: 'Meri Bookings',
  safetyCenter: 'Safety Center',
  referAndEarn: 'Refer Karein aur ₹200 Paayein',
  offers: 'Offers & Discounts',
  language: 'App ki Bhasha',
  logout: 'Logout',
};
